### ISSUE TITLE
Double check market math

### ISSUE THREAD

**Issue by alexmiddeleer** [matt-kimball/epc#5]
Hey Matt... if you have any time, the one thing that worries me about markets is whether I did the odds + influence graph math correctly. Actually, to be honest I didn't actually do the math, but I think this logic checks out.

I imported a couple of decks without markets and screenshot'ed the outputs for graph+table. I then added markets and compared the two. I expected the power odds table and influence graph for existing main deck cards to remain identical, as well as the graph's arcs and scale. This is because you cannot draw cards in your market, so they should not influence any of the existing output. As for the market card values, I was satisfied with reasonable looking numbers because they are going through the same code. Because results matched these expectations, I'm pretty sure everything is working properly. 

Also, right now we are ignoring merchants in our analysis. We may in the future want to treat market cards with less than 3 power as 3-drops (although that too might be wrong since you might be able to use temporary power to cast a merchant in some crazy edge case scenarios).

Does this make sense and seem reasonable, or should we do some testing with more rigor?

**Comment by matt-kimball** [comment]
I'm satisfied nothing has been broken by your changes.  Because you are recording the market cards in  `deck.marketCount` instead of `deck.cardCount`, the math should be unchanged.  Good choice.

When making changes to the deck code, in the past I've been running `epcTest()` in the Javascript console.  If tests fail, an assertion will fail.  Those tests still pass.

It would be good to add a new test there, in `epc-test.js`, which asserts that the market cards don't change the probabilities when added to the deck.

**Comment by matt-kimball** [comment]
I've assigned this issue back to you, and assume you will close it after adding that test I mentioned.
